# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeometrySample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeometrySample
  pod 'Result', '~> 3.0.0'

  target 'GeometrySampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
